name: MagicChat
version: ${projectVersion}
main: com.magicrealms.magicchat.core.BukkitMagicChat
api-version: 1.21
author: Ryan0916
commands:
  MagicChat:
    description: '魔法领域-聊天'
depend:
  - MagicLib
